openapi: 3.0.0
info:
  title: Products API
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        200:
          description: Products retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        500:
          description: Internal Server Error

  /api/products/{productId}:
    get:
      summary: Get a product by its ID
      tags:
        - Products
      parameters:
        - in: path
          name: productId
          required: true
          description: ID of the product
          schema:
            type: string
      responses:
        200:
          description: Product retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          description: Internal Server Error

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID of the product
        title:
          type: string
          description: Title of the product
        description:
          type: string
          description: Description of the product
        price:
    
